apiVersion: v2
name: go-http-cache-server
description: A Helm chart for the Go Gradle remote build cache server
type: application
version: 0.1.7
appVersion: "0.1.0"
home: https://github.com/AKrumov/go-http-cache-server
icon: https://raw.githubusercontent.com/AKrumov/go-http-cache-server/main/docs/logo.png
keywords:
  - gradle
  - build-cache
  - remote-cache
  - s3
  - prometheus
  - kubernetes
sources:
  - https://github.com/AKrumov/go-http-cache-server
maintainers:
  - name: AKrumov
    url: https://github.com/AKrumov
annotations:
  artifacthub.io/category: integration-delivery
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: source
      url: https://github.com/AKrumov/go-http-cache-server
    - name: support
      url: https://github.com/AKrumov/go-http-cache-server/issues
  artifacthub.io/images: |
    - name: go-http-cache-server
      image: ghcr.io/akrumov/go-http-cache-server:latest
      platforms:
        - linux/amd64
