replicaCount: 2

image:
  repository: ghcr.io/akrumov/go-gradle-cache
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80

config:
  storageType: s3
  localDir: /app/cache-data
  s3Bucket: my-gradle-cache
  s3Prefix: gradle-cache
  s3Region: us-east-1
  s3Endpoint: ""
  maxUploadSize: ""

secret:
  create: true
  name: ""
  data:
    AWS_ACCESS_KEY_ID: ""
    AWS_SECRET_ACCESS_KEY: ""
    AWS_SESSION_TOKEN: ""

args: []

resources:
  requests:
    memory: 128Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 1000m

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

persistence:
  enabled: false
  mountPath: /app/cache-data
  existingClaim: ""
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 10Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

nodeSelector: {}
tolerations: []
affinity: {}
