apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-gradle-cache.fullname" . }}-config
  labels:
    {{- include "go-gradle-cache.labels" . | nindent 4 }}
data:
  STORAGE_TYPE: {{ .Values.config.storageType | quote }}
  LOCAL_DIR: {{ .Values.config.localDir | quote }}
  S3_BUCKET: {{ .Values.config.s3Bucket | quote }}
  S3_PREFIX: {{ .Values.config.s3Prefix | quote }}
  S3_REGION: {{ .Values.config.s3Region | quote }}
  S3_ENDPOINT: {{ .Values.config.s3Endpoint | quote }}
  {{- if .Values.config.s3Concurrency }}
  S3_CONCURRENCY: {{ .Values.config.s3Concurrency | quote }}
  {{- end }}
  {{- if .Values.config.maxUploadSize }}
  MAX_UPLOAD_SIZE: {{ .Values.config.maxUploadSize | quote }}
  {{- end }}
